package io.github.luciegrillo.civitas.app.artifact;

import io.github.luciegrillo.civitas.app.VersionInfo;
import io.github.luciegrillo.civitas.app.config.ExperimentSpec;
import io.github.luciegrillo.civitas.app.config.InitializationType;
import io.github.luciegrillo.civitas.app.config.ScenarioSpec;
import io.github.luciegrillo.civitas.app.experiment.AggregateSummary;
import io.github.luciegrillo.civitas.app.experiment.RunResult;
import io.github.luciegrillo.civitas.app.json.JsonSupport;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import tools.jackson.core.JacksonException;

/**
 * Generates a deterministic, self-contained HTML summary for schema 0.2
 * experiments.
 */
public final class HtmlReportWriter {
    public static final String FILE_NAME = "report.html";

    private HtmlReportWriter() {
    }

    /**
     * Writes one standalone report with inline CSS, configuration, result
     * tables, and embedded PNG figures.
     */
    public static void write(
            Path path,
            ExperimentSpec experiment,
            List<RunResult> results,
            List<AggregateSummary> aggregates,
            Path figuresDirectory) throws IOException {
        Objects.requireNonNull(path, "path");
        Objects.requireNonNull(experiment, "experiment");
        Objects.requireNonNull(results, "results");
        Objects.requireNonNull(aggregates, "aggregates");
        Objects.requireNonNull(figuresDirectory, "figuresDirectory");

        StringBuilder html = new StringBuilder(128 * 1024);
        appendDocumentStart(html, experiment, results.size());
        appendScenarios(html, experiment.scenarios());
        appendResults(html, aggregates);
        appendFigures(html, figuresDirectory);
        appendConfiguration(html, experiment);
        appendReproduction(html);
        html.append("</main><footer>Generated by Civitas Lab ")
                .append(escape(VersionInfo.version()))
                .append(". Scientific claims remain conditional on the declared model and parameters."
                        + "</footer></body></html>\n");

        Files.writeString(path, html, StandardCharsets.UTF_8);
    }

    private static void appendDocumentStart(
            StringBuilder html, ExperimentSpec experiment, int runCount) {
        html.append("""
                <!doctype html>
                <html lang="en">
                <head>
                  <meta charset="utf-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1">
                  <title>""")
                .append(escape(experiment.experimentId()))
                .append(" — Civitas Lab</title>\n")
                .append("""
                  <style>
                    :root { color-scheme: light dark; font-family: system-ui, sans-serif; }
                    body { margin: 0; background: #f4f4f1; color: #191919; line-height: 1.5; }
                    header { background: #111; color: #fff; padding: 2.5rem max(1.5rem, calc((100vw - 1120px) / 2)); }
                    main, footer { max-width: 1120px; margin: auto; padding: 1.5rem; }
                    h1, h2 { line-height: 1.15; }
                    h2 { margin-top: 2.4rem; border-bottom: 2px solid #222; padding-bottom: .35rem; }
                    .eyebrow { text-transform: uppercase; letter-spacing: .12em; font-size: .78rem; opacity: .75; }
                    .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: .8rem; margin-top: 1.4rem; }
                    .card { background: #fff; border: 1px solid #ccc; border-radius: .55rem; padding: 1rem; }
                    .card strong { display: block; font-size: 1.45rem; }
                    .table-wrap { overflow-x: auto; background: #fff; border: 1px solid #ccc; border-radius: .55rem; }
                    table { border-collapse: collapse; width: 100%; font-size: .9rem; }
                    th, td { padding: .62rem .7rem; border-bottom: 1px solid #ddd; text-align: right; white-space: nowrap; }
                    th:first-child, td:first-child { text-align: left; }
                    th { background: #e9e9e5; }
                    figure { margin: 1.4rem 0; background: #fff; border: 1px solid #ccc; border-radius: .55rem; padding: .8rem; }
                    img { display: block; max-width: 100%; height: auto; margin: auto; }
                    figcaption { margin-top: .6rem; font-size: .9rem; text-align: center; }
                    pre { overflow-x: auto; background: #191919; color: #f5f5f5; padding: 1rem; border-radius: .55rem; }
                    code { font-family: ui-monospace, monospace; }
                    .note { border-left: .3rem solid #555; padding: .6rem 1rem; background: #fff; }
                    footer { font-size: .85rem; color: #555; padding-bottom: 3rem; }
                    @media (prefers-color-scheme: dark) {
                      body { background: #171717; color: #eee; }
                      header { background: #050505; }
                      .card, .table-wrap, figure, .note { background: #242424; border-color: #555; }
                      th { background: #303030; }
                      th, td { border-color: #494949; }
                      h2 { border-color: #ddd; }
                      footer { color: #aaa; }
                    }
                  </style>
                </head>
                <body>
                <header>
                  <div class="eyebrow">Civitas Lab experiment report</div>
                  <h1>""")
                .append(escape(experiment.experimentId()))
                .append("</h1>\n<p>Deterministic summary of a versioned spatial-game experiment.</p>\n")
                .append("<div class=\"cards\">")
                .append(card("Schema", experiment.schemaVersion()))
                .append(card("Runs", Integer.toString(runCount)))
                .append(card("Scenarios", Integer.toString(experiment.scenarios().size())))
                .append(card("Master seed", Long.toString(experiment.masterSeed())))
                .append("</div></header><main>\n")
                .append("<p class=\"note\">This report contains deterministic scientific summaries and embedded figures. "
                        + "Runtime-specific metadata remains in <code>provenance.json</code>, and full-precision data remains in the sibling CSV artifacts.</p>\n");
    }

    private static String card(String label, String value) {
        return "<div class=\"card\"><span>" + escape(label) + "</span><strong>"
                + escape(value) + "</strong></div>";
    }

    private static void appendScenarios(StringBuilder html, List<ScenarioSpec> scenarios) {
        html.append("<h2>Scenario design</h2><div class=\"table-wrap\"><table><thead><tr>")
                .append("<th>Scenario</th><th>Schedule</th><th>Lattice</th><th>Initialization</th>")
                .append("<th>Self interaction</th><th>Temptation values</th><th>Replicates</th>")
                .append("<th>Ticks</th><th>Measurement start</th></tr></thead><tbody>\n");
        for (ScenarioSpec scenario : scenarios) {
            String initialization = scenario.initialization().type().name();
            if (scenario.initialization().type() == InitializationType.BERNOULLI) {
                initialization += " p(C)=" + format(scenario.initialization().pCooperator());
            }
            String lattice = scenario.lattice().width() + " × " + scenario.lattice().height()
                    + " " + scenario.lattice().boundary();
            String temptation = scenario.temptationValues().stream()
                    .map(HtmlReportWriter::format)
                    .reduce((left, right) -> left + ", " + right)
                    .orElse("—");
            html.append("<tr><td>").append(escape(scenario.id())).append("</td><td>")
                    .append(escape(scenario.effectiveUpdateSchedule().type().name()))
                    .append("</td><td>").append(escape(lattice))
                    .append("</td><td>").append(escape(initialization))
                    .append("</td><td>").append(scenario.selfInteraction())
                    .append("</td><td>").append(escape(temptation))
                    .append("</td><td>").append(scenario.replicates())
                    .append("</td><td>").append(scenario.ticks())
                    .append("</td><td>").append(scenario.measurementStart())
                    .append("</td></tr>\n");
        }
        html.append("</tbody></table></div>\n");
    }

    private static void appendResults(
            StringBuilder html, List<AggregateSummary> aggregates) {
        html.append("<h2>Aggregate results</h2><div class=\"table-wrap\"><table><thead><tr>")
                .append("<th>Scenario</th><th>Schedule</th><th>b</th><th>Runs</th>")
                .append("<th>Final median</th><th>Final q05</th><th>Final q95</th>")
                .append("<th>All defect</th><th>Measurement C mean</th><th>Flip-rate mean</th>")
                .append("</tr></thead><tbody>\n");
        for (AggregateSummary aggregate : aggregates) {
            html.append("<tr><td>").append(escape(aggregate.scenarioId()))
                    .append("</td><td>")
                    .append(aggregate.updateSchedule() == null
                            ? "SYNCHRONOUS"
                            : escape(aggregate.updateSchedule().name()))
                    .append("</td><td>").append(format(aggregate.temptation()))
                    .append("</td><td>").append(aggregate.runs())
                    .append("</td><td>").append(format(aggregate.finalMedian()))
                    .append("</td><td>").append(format(aggregate.finalQ05()))
                    .append("</td><td>").append(format(aggregate.finalQ95()))
                    .append("</td><td>").append(format(aggregate.allDefectRate()))
                    .append("</td><td>")
                    .append(format(aggregate.measurementMeanCooperatorFraction()))
                    .append("</td><td>")
                    .append(format(aggregate.measurementMeanFlipRate()))
                    .append("</td></tr>\n");
        }
        html.append("</tbody></table></div>\n");
    }

    private static void appendFigures(StringBuilder html, Path figuresDirectory)
            throws IOException {
        if (!Files.isDirectory(figuresDirectory)) {
            return;
        }
        List<Path> figures;
        try (var paths = Files.list(figuresDirectory)) {
            figures = paths.filter(Files::isRegularFile)
                    .filter(path -> path.getFileName().toString().endsWith(".png"))
                    .sorted()
                    .toList();
        }
        if (figures.isEmpty()) {
            return;
        }

        html.append("<h2>Figures</h2>\n");
        Base64.Encoder encoder = Base64.getEncoder();
        for (Path figure : figures) {
            String name = figure.getFileName().toString();
            String encoded = encoder.encodeToString(Files.readAllBytes(figure));
            String caption = name.substring(0, name.length() - 4)
                    .replace('-', ' ');
            html.append("<figure><img alt=\"")
                    .append(escape(caption))
                    .append("\" src=\"data:image/png;base64,")
                    .append(encoded)
                    .append("\"><figcaption>")
                    .append(escape(caption))
                    .append("</figcaption></figure>\n");
        }
    }

    private static void appendConfiguration(
            StringBuilder html, ExperimentSpec experiment) throws IOException {
        String json;
        try {
            json = JsonSupport.mapper()
                    .writerWithDefaultPrettyPrinter()
                    .writeValueAsString(experiment);
        } catch (JacksonException exception) {
            throw new IOException("could not render experiment JSON in HTML report", exception);
        }
        html.append("<h2>Resolved configuration</h2><pre><code>")
                .append(escape(json))
                .append("</code></pre>\n");
    }

    private static void appendReproduction(StringBuilder html) {
        html.append("""
                <h2>Reproduction and integrity</h2>
                <p>Save this report beside the generated artifacts. The resolved configuration can be executed directly:</p>
                <pre><code>java -jar civitas-lab.jar run resolved-experiment.json --output reproduced
                java -jar civitas-lab.jar validate reproduced</code></pre>
                <p><code>checksums.sha256</code> covers this report and all deterministic scientific artifacts. Use the CLI validation command to detect missing or modified files.</p>
                """);
    }

    private static String format(double value) {
        return String.format(Locale.ROOT, "%.4f", value);
    }

    private static String escape(String value) {
        return value.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
